### ISSUE TITLE
Add ESLint to CI

### ISSUE THREAD

**Issue by kenjiwilkins** [kenjiwilkins/phonograph#11]
**Is your feature request related to a problem? Please describe.**
Currently CI only formats codes by prettier but there is no linter.

**Describe the solution you'd like**
Add eslint and rules to match with vue, typescript and prettier

**Describe alternatives you've considered**
Is there any?

**Additional context**
I tried to implement ESlint once while adding GitHub Actions. But error occurs on run eslint, some kind of error inside dependencies.

**Comment by averrois** [comment]
can I take a chance on this one!

**Comment by kenjiwilkins** [comment]
Hi @averrois ,

Thank you for your volunteer!

The requirements from me are:

- Install eslint and plugins for typescript and vue3. 
- Add eslint config file and rules to apply plugins. 
  - However, please be careful not to conflict with prettier.
- add eslint to GHA workflow
- Fix or `ts-ignore` codes causing error on lint

But if you have any better solution, feel free to enlighten me! 😄 

I will assign you to this issue now.

**Comment by averrois** [comment]
alright...

**Comment by averrois** [comment]
is there an reason way u are using and older version of @typescript-eslint/eslint-plugin !

**Comment by kenjiwilkins** [comment]
That's because some runtime error occurs on while running eslint on latest eslint and plugins.
Seemed like some package inside eslint but not quite sure.
I was trying to find the difference between older version but haven't find the reason yet...

**Comment by averrois** [comment]
ooh I see, I may self I am getting warning about ts-eslint, for  not supporting the current version of TS, when I look it up most solution that I find is downgrade version of TS, but since I am knw to this  lol, I am not quit  sure if this a good approach !

**Comment by kenjiwilkins** [comment]
@averrois 
You're right. We supposed not to keep using the older version to accept the vulnerability ...

In my local environment, it seems like an error on eslint built-in default formatter `stylish.js`.
I don't know why this causes an error in typescript env it never happened in other projects I have.
<img width="1092" alt="Screenshot 2024-03-30 at 22 02 00" src="https://github.com/kenjiwilkins/phonograph/assets/19940324/0e16d56a-b776-4cc1-8486-7e2f5a088086">

If I change formatter to other options suitable for command line such as `compact` or `visualstudio`, it works well.
<img width="1081" alt="Screenshot 2024-03-30 at 22 04 35" src="https://github.com/kenjiwilkins/phonograph/assets/19940324/6f9a4b53-ded7-441f-b7c4-63af82baf993">

Maybe we can simply use this.
Please checkout the demo branch I pushed on #18 

This could fix the problem for now... 🤔

**Comment by averrois** [comment]
it's nice to knw that u fix it...,

**Comment by averrois** [comment]
I tried it, and it works , as you said it might solve the issue for the moment...
